### ISSUE TITLE
Support for Studio 21

### ISSUE THREAD

**Issue by stelmath** [EvzenP/STraSAK#4]
Hi there, I am using the new Studio 21 trial version but I get a ton of errors when using the scripts of the repo. Do you plan on releasing support for this latest update? Thanks!

**Comment by EvzenP** [comment]
As I'm not in localization industry anymore, STraSAK got out of my focus somehow and I'm not following the Studio developments too closely.

Yet, it's nice to hear that STraSAK is actually used by someone... Let me check in the coming days what can be done, hopefully it will be about some simple amendments only, not requiring additional changes due to changed Studio API, or so.

**Comment by stelmath** [comment]
From the little I looked at, there are some file path changes and files moved around or completely renamed. I would appreciate any effort you might put in, thanks!

**Comment by EvzenP** [comment]
Check the version 1.8, according to my (very quick) testing it should work.

**Comment by stelmath** [comment]
@EvzenP thank you for the swift actions! I am curious though, why did you choose to use shell scripts to manipulate Trados instead of using C# to work with the actual code base of Trados and automate it that way? There is online documentation and examples of such C# API from the SDL Trados official website. Anyway, thanks!

**Comment by EvzenP** [comment]
The reason is that I'm a **scripter**, not a programmer.

In the good old pre-Studio days of Trados, one could automate Trados using ActiveX. This was extremely simple even for non-programmers (e.g. using JScript, which could be used for scripting Office too).

Unfortunately, with Studio, SDL dropped the ActiveX support completely, ignoring the fact that not everybody is a C# programmer and that not everybody is a _GUI-clicker_ (i.e. not everybody wants to use their GUI-plugins concept, apparently made rather for the translators than for engineers)... so people like me needed to find some new way to do what they needed...
And the only acceptable way for me was the PowerShell, which combines both the classical scripting approach AND access to the .NET API (as the only way to automate Studio).
I did NOT want to use any pre-compiled binaries, as I wanted to keep the functionality to be extendable/modifiable by anybody in the company **without any need for compilation**, i.e. I wanted the people to be able to just modify the source and see the new functionality immediately...

So, that's the story ;-)

**Comment by EvzenP** [comment]
Oh, and if it's not clear enough - this of course uses the same Studio API as the plugins... i.e. I go to the very same documentation for description of the API, etc.
